export const CITIES = [
  { name: 'Adana', value: 'Adana' },
  { name: 'Adıyaman', value: 'Adıyaman' },
  { name: 'Afyon', value: 'Afyon' },
  { name: 'Ağrı', value: 'Ağrı' },
  { name: 'Amasya', value: 'Amasya' },
  { name: 'Ankara', value: 'Ankara' },
  { name: 'Antalya', value: 'Antalya' },
  { name: 'Artvin', value: 'Artvin' },
  { name: 'Aydın', value: 'Aydın' },
  { name: 'Balıkesir', value: 'Balıkesir' },
  { name: 'Bilecik', value: 'Bilecik' },
  { name: 'Bingöl', value: 'Bingöl' },
  { name: 'Bitlis', value: 'Bitlis' },
  { name: 'Bolu', value: 'Bolu' },
  { name: 'Burdur', value: 'Burdur' },
  { name: 'Bursa', value: 'Bursa' },
  { name: 'Çanakkale', value: 'Çanakkale' },
  { name: 'Çankırı', value: 'Çankırı' },
  { name: 'Çorum', value: 'Çorum' },
  { name: 'Denizli', value: 'Denizli' },
  { name: 'Diyarbakır', value: 'Diyarbakır' },
  { name: 'Edirne', value: 'Edirne' },
  { name: 'Elazığ', value: 'Elazığ' },
  { name: 'Erzincan', value: 'Erzincan' },
  { name: 'Erzurum', value: 'Erzurum' },
  { name: 'Eskişehir', value: 'Eskişehir' },
  { name: 'Gaziantep', value: 'Gaziantep' },
  { name: 'Giresun', value: 'Giresun' },
  { name: 'Gümüşhane', value: 'Gümüşhane' },
  { name: 'Hakkari', value: 'Hakkari' },
  { name: 'Hatay', value: 'Hatay' },
  { name: 'Isparta', value: 'Isparta' },
  { name: 'Mersin', value: 'Mersin' },
  { name: 'İstanbul', value: 'İstanbul' },
  { name: 'İzmir', value: 'İzmir' },
  { name: 'Kars', value: 'Kars' },
  { name: 'Kastamonu', value: 'Kastamonu' },
  { name: 'Kayseri', value: 'Kayseri' },
  { name: 'Kırklareli', value: 'Kırklareli' },
  { name: 'Kırşehir', value: 'Kırşehir' },
  { name: 'Kocaeli', value: 'Kocaeli' },
  { name: 'Konya', value: 'Konya' },
  { name: 'Kütahya', value: 'Kütahya' },
  { name: 'Malatya', value: 'Malatya' },
  { name: 'Manisa', value: 'Manisa' },
  { name: 'Kahramanmaraş', value: 'Kahramanmaraş' },
  { name: 'Mardin', value: 'Mardin' },
  { name: 'Muğla', value: 'Muğla' },
  { name: 'Muş', value: 'Muş' },
  { name: 'Nevşehir', value: 'Nevşehir' },
  { name: 'Niğde', value: 'Niğde' },
  { name: 'Ordu', value: 'Ordu' },
  { name: 'Rize', value: 'Rize' },
  { name: 'Sakarya', value: 'Sakarya' },
  { name: 'Samsun', value: 'Samsun' },
  { name: 'Siirt', value: 'Siirt' },
  { name: 'Sinop', value: 'Sinop' },
  { name: 'Sivas', value: 'Sivas' },
  { name: 'Tekirdağ', value: 'Tekirdağ' },
  { name: 'Tokat', value: 'Tokat' },
  { name: 'Trabzon', value: 'Trabzon' },
  { name: 'Tunceli', value: 'Tunceli' },
  { name: 'Şanlıurfa', value: 'Şanlıurfa' },
  { name: 'Uşak', value: 'Uşak' },
  { name: 'Van', value: 'Van' },
  { name: 'Yozgat', value: 'Yozgat' },
  { name: 'Zonguldak', value: 'Zonguldak' },
  { name: 'Aksaray', value: 'Aksaray' },
  { name: 'Bayburt', value: 'Bayburt' },
  { name: 'Karaman', value: 'Karaman' },
  { name: 'Kırıkkale', value: 'Kırıkkale' },
  { name: 'Batman', value: 'Batman' },
  { name: 'Şırnak', value: 'Şırnak' },
  { name: 'Bartın', value: 'Bartın' },
  { name: 'Ardahan', value: 'Ardahan' },
  { name: 'Iğdır', value: 'Iğdır' },
  { name: 'Yalova', value: 'Yalova' },
  { name: 'Karabük', value: 'Karabük' },
  { name: 'Kilis', value: 'Kilis' },
  { name: 'Osmaniye', value: 'Osmaniye' },
  { name: 'Düzce', value: 'Düzce' },
]

export const DISTRICTS: { [key: string]: { name: string; value: string }[] } = {
  Adana: [
    { name: 'Aladağ', value: 'Aladağ' },
    { name: 'Ceyhan', value: 'Ceyhan' },
    { name: 'Çukurova', value: 'Çukurova' },
    { name: 'Feke', value: 'Feke' },
    { name: 'İmamoğlu', value: 'İmamoğlu' },
    { name: 'Karaisalı', value: 'Karaisalı' },
    { name: 'Karataş', value: 'Karataş' },
    { name: 'Kozan', value: 'Kozan' },
    { name: 'Pozantı', value: 'Pozantı' },
    { name: 'Saimbeyli', value: 'Saimbeyli' },
    { name: 'Sarıçam', value: 'Sarıçam' },
    { name: 'Seyhan', value: 'Seyhan' },
    { name: 'Tufanbeyli', value: 'Tufanbeyli' },
    { name: 'Yumurtalık', value: 'Yumurtalık' },
    { name: 'Yüreğir', value: 'Yüreğir' },
  ],
  Adıyaman: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Besni', value: 'Besni' },
    { name: 'Çelikhan', value: 'Çelikhan' },
    { name: 'Gerger', value: 'Gerger' },
    { name: 'Gölbaşı', value: 'Gölbaşı' },
    { name: 'Kâhta', value: 'Kâhta' },
    { name: 'Samsat', value: 'Samsat' },
    { name: 'Sincik', value: 'Sincik' },
    { name: 'Tut', value: 'Tut' },
  ],
  Afyon: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Başmakçı', value: 'Başmakçı' },
    { name: 'Bayat', value: 'Bayat' },
    { name: 'Bolvadin', value: 'Bolvadin' },
    { name: 'Çay', value: 'Çay' },
    { name: 'Çobanlar', value: 'Çobanlar' },
    { name: 'Dazkırı', value: 'Dazkırı' },
    { name: 'Dinar', value: 'Dinar' },
    { name: 'Emirdağ', value: 'Emirdağ' },
    { name: 'Evciler', value: 'Evciler' },
    { name: 'Hocalar', value: 'Hocalar' },
    { name: 'İhsaniye', value: 'İhsaniye' },
    { name: 'İscehisar', value: 'İscehisar' },
    { name: 'Kızılören', value: 'Kızılören' },
    { name: 'Sandıklı', value: 'Sandıklı' },
    { name: 'Sinanpaşa', value: 'Sinanpaşa' },
    { name: 'Sultandağı', value: 'Sultandağı' },
    { name: 'Şuhut', value: 'Şuhut' },
  ],
  Ağrı: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Diyadin', value: 'Diyadin' },
    { name: 'Doğubayazıt', value: 'Doğubayazıt' },
    { name: 'Eleşkirt', value: 'Eleşkirt' },
    { name: 'Hamur', value: 'Hamur' },
    { name: 'Patnos', value: 'Patnos' },
    { name: 'Taşlıçay', value: 'Taşlıçay' },
    { name: 'Tutak', value: 'Tutak' },
  ],
  Amasya: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Göynücek', value: 'Göynücek' },
    { name: 'Gümüşhacıköy', value: 'Gümüşhacıköy' },
    { name: 'Hamamözü', value: 'Hamamözü' },
    { name: 'Merzifon', value: 'Merzifon' },
    { name: 'Suluova', value: 'Suluova' },
    { name: 'Taşova', value: 'Taşova' },
  ],
  Ankara: [
    { name: 'Akyurt', value: 'Akyurt' },
    { name: 'Altındağ', value: 'Altındağ' },
    { name: 'Ayaş', value: 'Ayaş' },
    { name: 'Balâ', value: 'Balâ' },
    { name: 'Beypazarı', value: 'Beypazarı' },
    { name: 'Çamlıdere', value: 'Çamlıdere' },
    { name: 'Çankaya', value: 'Çankaya' },
    { name: 'Çubuk', value: 'Çubuk' },
    { name: 'Elmadağ', value: 'Elmadağ' },
    { name: 'Etimesgut', value: 'Etimesgut' },
    { name: 'Evren', value: 'Evren' },
    { name: 'Gölbaşı', value: 'Gölbaşı' },
    { name: 'Güdül', value: 'Güdül' },
    { name: 'Haymana', value: 'Haymana' },
    { name: 'Kalecik', value: 'Kalecik' },
    { name: 'Kahramankazan', value: 'Kahramankazan' },
    { name: 'Keçiören', value: 'Keçiören' },
    { name: 'Kızılcahamam', value: 'Kızılcahamam' },
    { name: 'Mamak', value: 'Mamak' },
    { name: 'Nallıhan', value: 'Nallıhan' },
    { name: 'Polatlı', value: 'Polatlı' },
    { name: 'Pursaklar', value: 'Pursaklar' },
    { name: 'Sincan', value: 'Sincan' },
    { name: 'Şereflikoçhisar', value: 'Şereflikoçhisar' },
    { name: 'Yenimahalle', value: 'Yenimahalle' },
  ],
  Antalya: [
    { name: 'Akseki', value: 'Akseki' },
    { name: 'Aksu', value: 'Aksu' },
    { name: 'Alanya', value: 'Alanya' },
    { name: 'Demre', value: 'Demre' },
    { name: 'Döşemealtı', value: 'Döşemealtı' },
    { name: 'Elmalı', value: 'Elmalı' },
    { name: 'Finike', value: 'Finike' },
    { name: 'Gazipaşa', value: 'Gazipaşa' },
    { name: 'Gündoğmuş', value: 'Gündoğmuş' },
    { name: 'İbradı', value: 'İbradı' },
    { name: 'Kaş', value: 'Kaş' },
    { name: 'Kemer', value: 'Kemer' },
    { name: 'Kepez', value: 'Kepez' },
    { name: 'Konyaaltı', value: 'Konyaaltı' },
    { name: 'Korkuteli', value: 'Korkuteli' },
    { name: 'Kumluca', value: 'Kumluca' },
    { name: 'Manavgat', value: 'Manavgat' },
    { name: 'Muratpaşa', value: 'Muratpaşa' },
    { name: 'Serik', value: 'Serik' },
  ],
  Artvin: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ardanuç', value: 'Ardanuç' },
    { name: 'Arhavi', value: 'Arhavi' },
    { name: 'Borçka', value: 'Borçka' },
    { name: 'Hopa', value: 'Hopa' },
    { name: 'Kemalpaşa', value: 'Kemalpaşa' },
    { name: 'Murgul', value: 'Murgul' },
    { name: 'Şavşat', value: 'Şavşat' },
    { name: 'Yusufeli', value: 'Yusufeli' },
  ],
  Aydın: [
    { name: 'Bozdoğan', value: 'Bozdoğan' },
    { name: 'Buharkent', value: 'Buharkent' },
    { name: 'Çine', value: 'Çine' },
    { name: 'Didim', value: 'Didim' },
    { name: 'Efeler', value: 'Efeler' },
    { name: 'Germencik', value: 'Germencik' },
    { name: 'İncirliova', value: 'İncirliova' },
    { name: 'Karacasu', value: 'Karacasu' },
    { name: 'Karpuzlu', value: 'Karpuzlu' },
    { name: 'Koçarlı', value: 'Koçarlı' },
    { name: 'Köşk', value: 'Köşk' },
    { name: 'Kuşadası', value: 'Kuşadası' },
    { name: 'Kuyucak', value: 'Kuyucak' },
    { name: 'Nazilli', value: 'Nazilli' },
    { name: 'Söke', value: 'Söke' },
    { name: 'Sultanhisar', value: 'Sultanhisar' },
    { name: 'Yenipazar', value: 'Yenipazar' },
  ],
  Balıkesir: [
    { name: 'Altıeylül', value: 'Altıeylül' },
    { name: 'Ayvalık', value: 'Ayvalık' },
    { name: 'Balya', value: 'Balya' },
    { name: 'Bandırma', value: 'Bandırma' },
    { name: 'Bigadiç', value: 'Bigadiç' },
    { name: 'Burhaniye', value: 'Burhaniye' },
    { name: 'Dursunbey', value: 'Dursunbey' },
    { name: 'Edremit', value: 'Edremit' },
    { name: 'Erdek', value: 'Erdek' },
    { name: 'Gömeç', value: 'Gömeç' },
    { name: 'Gönen', value: 'Gönen' },
    { name: 'Havran', value: 'Havran' },
    { name: 'İvrindi', value: 'İvrindi' },
    { name: 'Karesi', value: 'Karesi' },
    { name: 'Kepsut', value: 'Kepsut' },
    { name: 'Manyas', value: 'Manyas' },
    { name: 'Marmara', value: 'Marmara' },
    { name: 'Savaştepe', value: 'Savaştepe' },
    { name: 'Sındırgı', value: 'Sındırgı' },
    { name: 'Susurluk', value: 'Susurluk' },
  ],
  Bilecik: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Bozüyük', value: 'Bozüyük' },
    { name: 'Gölpazarı', value: 'Gölpazarı' },
    { name: 'İnhisar', value: 'İnhisar' },
    { name: 'Osmaneli', value: 'Osmaneli' },
    { name: 'Pazaryeri', value: 'Pazaryeri' },
    { name: 'Söğüt', value: 'Söğüt' },
    { name: 'Yenipazar', value: 'Yenipazar' },
  ],
  Bingöl: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Adaklı', value: 'Adaklı' },
    { name: 'Genç', value: 'Genç' },
    { name: 'Karlıova', value: 'Karlıova' },
    { name: 'Kiğı', value: 'Kiğı' },
    { name: 'Solhan', value: 'Solhan' },
    { name: 'Yayladere', value: 'Yayladere' },
    { name: 'Yedisu', value: 'Yedisu' },
  ],
  Bitlis: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Adilcevaz', value: 'Adilcevaz' },
    { name: 'Ahlat', value: 'Ahlat' },
    { name: 'Güroymak', value: 'Güroymak' },
    { name: 'Hizan', value: 'Hizan' },
    { name: 'Mutki', value: 'Mutki' },
    { name: 'Tatvan', value: 'Tatvan' },
  ],
  Bolu: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Dörtdivan', value: 'Dörtdivan' },
    { name: 'Gerede', value: 'Gerede' },
    { name: 'Göynük', value: 'Göynük' },
    { name: 'Kıbrıscık', value: 'Kıbrıscık' },
    { name: 'Mengen', value: 'Mengen' },
    { name: 'Mudurnu', value: 'Mudurnu' },
    { name: 'Seben', value: 'Seben' },
    { name: 'Yeniçağa', value: 'Yeniçağa' },
  ],
  Burdur: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ağlasun', value: 'Ağlasun' },
    { name: 'Altınyayla', value: 'Altınyayla' },
    { name: 'Bucak', value: 'Bucak' },
    { name: 'Çavdır', value: 'Çavdır' },
    { name: 'Çeltikçi', value: 'Çeltikçi' },
    { name: 'Gölhisar', value: 'Gölhisar' },
    { name: 'Karamanlı', value: 'Karamanlı' },
    { name: 'Kemer', value: 'Kemer' },
    { name: 'Tefenni', value: 'Tefenni' },
    { name: 'Yeşilova', value: 'Yeşilova' },
  ],
  Bursa: [
    { name: 'Büyükorhan', value: 'Büyükorhan' },
    { name: 'Gemlik', value: 'Gemlik' },
    { name: 'Gürsu', value: 'Gürsu' },
    { name: 'Harmancık', value: 'Harmancık' },
    { name: 'İnegöl', value: 'İnegöl' },
    { name: 'İznik', value: 'İznik' },
    { name: 'Karacabey', value: 'Karacabey' },
    { name: 'Keles', value: 'Keles' },
    { name: 'Kestel', value: 'Kestel' },
    { name: 'Mudanya', value: 'Mudanya' },
    { name: 'Mustafa Kemal Paşa', value: 'Mustafa Kemal Paşa' },
    { name: 'Nilüfer', value: 'Nilüfer' },
    { name: 'Orhaneli', value: 'Orhaneli' },
    { name: 'Orhangazi', value: 'Orhangazi' },
    { name: 'Osmangazi', value: 'Osmangazi' },
    { name: 'Yenişehir', value: 'Yenişehir' },
    { name: 'Yıldırım', value: 'Yıldırım' },
  ],
  Çanakkale: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ayvacık', value: 'Ayvacık' },
    { name: 'Bayramiç', value: 'Bayramiç' },
    { name: 'Biga', value: 'Biga' },
    { name: 'Bozcaada', value: 'Bozcaada' },
    { name: 'Çan', value: 'Çan' },
    { name: 'Eceabat', value: 'Eceabat' },
    { name: 'Ezine', value: 'Ezine' },
    { name: 'Gelibolu', value: 'Gelibolu' },
    { name: 'Gökçeada', value: 'Gökçeada' },
    { name: 'Lapseki', value: 'Lapseki' },
    { name: 'Yenice', value: 'Yenice' },
  ],
  Çankırı: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Atkaracalar', value: 'Atkaracalar' },
    { name: 'Bayramören', value: 'Bayramören' },
    { name: 'Çerkeş', value: 'Çerkeş' },
    { name: 'Eldivan', value: 'Eldivan' },
    { name: 'Ilgaz', value: 'Ilgaz' },
    { name: 'Kızılırmak', value: 'Kızılırmak' },
    { name: 'Korgun', value: 'Korgun' },
    { name: 'Kurşunlu', value: 'Kurşunlu' },
    { name: 'Orta', value: 'Orta' },
    { name: 'Şabanözü', value: 'Şabanözü' },
    { name: 'Yapraklı', value: 'Yapraklı' },
  ],
  Çorum: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Alaca', value: 'Alaca' },
    { name: 'Bayat', value: 'Bayat' },
    { name: 'Boğazkale', value: 'Boğazkale' },
    { name: 'Dodurga', value: 'Dodurga' },
    { name: 'İskilip', value: 'İskilip' },
    { name: 'Kargı', value: 'Kargı' },
    { name: 'Laçin', value: 'Laçin' },
    { name: 'Mecitözü', value: 'Mecitözü' },
    { name: 'Oğuzlar', value: 'Oğuzlar' },
    { name: 'Ortaköy', value: 'Ortaköy' },
    { name: 'Osmancık', value: 'Osmancık' },
    { name: 'Sungurlu', value: 'Sungurlu' },
    { name: 'Uğurludağ', value: 'Uğurludağ' },
  ],
  Denizli: [
    { name: 'Acıpayam', value: 'Acıpayam' },
    { name: 'Babadağ', value: 'Babadağ' },
    { name: 'Baklan', value: 'Baklan' },
    { name: 'Bekilli', value: 'Bekilli' },
    { name: 'Beyağaç', value: 'Beyağaç' },
    { name: 'Bozkurt', value: 'Bozkurt' },
    { name: 'Buldan', value: 'Buldan' },
    { name: 'Çal', value: 'Çal' },
    { name: 'Çameli', value: 'Çameli' },
    { name: 'Çardak', value: 'Çardak' },
    { name: 'Çivril', value: 'Çivril' },
    { name: 'Güney', value: 'Güney' },
    { name: 'Honaz', value: 'Honaz' },
    { name: 'Kale', value: 'Kale' },
    { name: 'Merkezefendi', value: 'Merkezefendi' },
    { name: 'Pamukkale', value: 'Pamukkale' },
    { name: 'Sarayköy', value: 'Sarayköy' },
    { name: 'Serinhisar', value: 'Serinhisar' },
    { name: 'Tavas', value: 'Tavas' },
  ],
  Diyarbakır: [
    { name: 'Bağlar', value: 'Bağlar' },
    { name: 'Bismil', value: 'Bismil' },
    { name: 'Çermik', value: 'Çermik' },
    { name: 'Çınar', value: 'Çınar' },
    { name: 'Çüngüş', value: 'Çüngüş' },
    { name: 'Dicle', value: 'Dicle' },
    { name: 'Eğil', value: 'Eğil' },
    { name: 'Ergani', value: 'Ergani' },
    { name: 'Hani', value: 'Hani' },
    { name: 'Hazro', value: 'Hazro' },
    { name: 'Kayapınar', value: 'Kayapınar' },
    { name: 'Kocaköy', value: 'Kocaköy' },
    { name: 'Kulp', value: 'Kulp' },
    { name: 'Lice', value: 'Lice' },
    { name: 'Silvan', value: 'Silvan' },
    { name: 'Sur', value: 'Sur' },
    { name: 'Yenişehir', value: 'Yenişehir' },
  ],
  Edirne: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Enez', value: 'Enez' },
    { name: 'Havsa', value: 'Havsa' },
    { name: 'İpsala', value: 'İpsala' },
    { name: 'Keşan', value: 'Keşan' },
    { name: 'Lalapaşa', value: 'Lalapaşa' },
    { name: 'Meriç', value: 'Meriç' },
    { name: 'Süloğlu', value: 'Süloğlu' },
    { name: 'Uzunköprü', value: 'Uzunköprü' },
  ],
  Elazığ: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ağın', value: 'Ağın' },
    { name: 'Alacakaya', value: 'Alacakaya' },
    { name: 'Arıcak', value: 'Arıcak' },
    { name: 'Baskil', value: 'Baskil' },
    { name: 'Karakoçan', value: 'Karakoçan' },
    { name: 'Keban', value: 'Keban' },
    { name: 'Kovancılar', value: 'Kovancılar' },
    { name: 'Maden', value: 'Maden' },
    { name: 'Palu', value: 'Palu' },
    { name: 'Sivrice', value: 'Sivrice' },
  ],
  Erzincan: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Çayırlı', value: 'Çayırlı' },
    { name: 'İliç', value: 'İliç' },
    { name: 'Kemah', value: 'Kemah' },
    { name: 'Kemaliye', value: 'Kemaliye' },
    { name: 'Otlukbeli', value: 'Otlukbeli' },
    { name: 'Refahiye', value: 'Refahiye' },
    { name: 'Tercan', value: 'Tercan' },
    { name: 'Üzümlü', value: 'Üzümlü' },
  ],
  Erzurum: [
    { name: 'Aşkale', value: 'Aşkale' },
    { name: 'Aziziye', value: 'Aziziye' },
    { name: 'Çat', value: 'Çat' },
    { name: 'Hınıs', value: 'Hınıs' },
    { name: 'Horasan', value: 'Horasan' },
    { name: 'İspir', value: 'İspir' },
    { name: 'Karaçoban', value: 'Karaçoban' },
    { name: 'Karayazı', value: 'Karayazı' },
    { name: 'Köprüköy', value: 'Köprüköy' },
    { name: 'Narman', value: 'Narman' },
    { name: 'Oltu', value: 'Oltu' },
    { name: 'Olur', value: 'Olur' },
    { name: 'Palandöken', value: 'Palandöken' },
    { name: 'Pasinler', value: 'Pasinler' },
    { name: 'Pazaryolu', value: 'Pazaryolu' },
    { name: 'Şenkaya', value: 'Şenkaya' },
    { name: 'Tekman', value: 'Tekman' },
    { name: 'Tortum', value: 'Tortum' },
    { name: 'Uzundere', value: 'Uzundere' },
    { name: 'Yakutiye', value: 'Yakutiye' },
  ],
  Eskişehir: [
    { name: 'Alpu', value: 'Alpu' },
    { name: 'Beylikova', value: 'Beylikova' },
    { name: 'Çifteler', value: 'Çifteler' },
    { name: 'Günyüzü', value: 'Günyüzü' },
    { name: 'Han', value: 'Han' },
    { name: 'İnönü', value: 'İnönü' },
    { name: 'Mahmudiye', value: 'Mahmudiye' },
    { name: 'Mihalgazi', value: 'Mihalgazi' },
    { name: 'Mihalıççık', value: 'Mihalıççık' },
    { name: 'Odunpazarı', value: 'Odunpazarı' },
    { name: 'Sarıcakaya', value: 'Sarıcakaya' },
    { name: 'Seyitgazi', value: 'Seyitgazi' },
    { name: 'Sivrihisar', value: 'Sivrihisar' },
    { name: 'Tepebaşı', value: 'Tepebaşı' },
  ],
  Gaziantep: [
    { name: 'Araban', value: 'Araban' },
    { name: 'İslahiye', value: 'İslahiye' },
    { name: 'Karkamış', value: 'Karkamış' },
    { name: 'Nizip', value: 'Nizip' },
    { name: 'Nurdağı', value: 'Nurdağı' },
    { name: 'Oğuzeli', value: 'Oğuzeli' },
    { name: 'Şahinbey', value: 'Şahinbey' },
    { name: 'Şehitkamil', value: 'Şehitkamil' },
    { name: 'Yavuzeli', value: 'Yavuzeli' },
  ],
  Giresun: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Alucra', value: 'Alucra' },
    { name: 'Bulancak', value: 'Bulancak' },
    { name: 'Çamoluk', value: 'Çamoluk' },
    { name: 'Çanakçı', value: 'Çanakçı' },
    { name: 'Dereli', value: 'Dereli' },
    { name: 'Doğankent', value: 'Doğankent' },
    { name: 'Espiye', value: 'Espiye' },
    { name: 'Eynesil', value: 'Eynesil' },
    { name: 'Görele', value: 'Görele' },
    { name: 'Güce', value: 'Güce' },
    { name: 'Keşap', value: 'Keşap' },
    { name: 'Piraziz', value: 'Piraziz' },
    { name: 'Şebinkarahisar', value: 'Şebinkarahisar' },
    { name: 'Tirebolu', value: 'Tirebolu' },
    { name: 'Yağlıdere', value: 'Yağlıdere' },
  ],
  Gümüşhane: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Kelkit', value: 'Kelkit' },
    { name: 'Köse', value: 'Köse' },
    { name: 'Kürtün', value: 'Kürtün' },
    { name: 'Şiran', value: 'Şiran' },
    { name: 'Torul', value: 'Torul' },
  ],
  Hakkari: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Çukurca', value: 'Çukurca' },
    { name: 'Derecik', value: 'Derecik' },
    { name: 'Şemdinli', value: 'Şemdinli' },
    { name: 'Yüksekova', value: 'Yüksekova' },
  ],
  Hatay: [
    { name: 'Altınözü', value: 'Altınözü' },
    { name: 'Antakya', value: 'Antakya' },
    { name: 'Arsuz', value: 'Arsuz' },
    { name: 'Belen', value: 'Belen' },
    { name: 'Defne', value: 'Defne' },
    { name: 'Dörtyol', value: 'Dörtyol' },
    { name: 'Erzin', value: 'Erzin' },
    { name: 'Hassa', value: 'Hassa' },
    { name: 'İskenderun', value: 'İskenderun' },
    { name: 'Kırıkhan', value: 'Kırıkhan' },
    { name: 'Kumlu', value: 'Kumlu' },
    { name: 'Payas', value: 'Payas' },
    { name: 'Reyhanlı', value: 'Reyhanlı' },
    { name: 'Samandağ', value: 'Samandağ' },
    { name: 'Yayladağı', value: 'Yayladağı' },
  ],
  Isparta: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Aksu', value: 'Aksu' },
    { name: 'Atabey', value: 'Atabey' },
    { name: 'Eğirdir', value: 'Eğirdir' },
    { name: 'Gelendost', value: 'Gelendost' },
    { name: 'Gönen', value: 'Gönen' },
    { name: 'Keçiborlu', value: 'Keçiborlu' },
    { name: 'Senirkent', value: 'Senirkent' },
    { name: 'Sütçüler', value: 'Sütçüler' },
    { name: 'Şarkikaraağaç', value: 'Şarkikaraağaç' },
    { name: 'Uluborlu', value: 'Uluborlu' },
    { name: 'Yalvaç', value: 'Yalvaç' },
    { name: 'Yenişarbademli', value: 'Yenişarbademli' },
  ],
  Mersin: [
    { name: 'Akdeniz', value: 'Akdeniz' },
    { name: 'Anamur', value: 'Anamur' },
    { name: 'Aydıncık', value: 'Aydıncık' },
    { name: 'Bozyazı', value: 'Bozyazı' },
    { name: 'Çamlıyayla', value: 'Çamlıyayla' },
    { name: 'Erdemli', value: 'Erdemli' },
    { name: 'Gülnar', value: 'Gülnar' },
    { name: 'Mezitli', value: 'Mezitli' },
    { name: 'Mut', value: 'Mut' },
    { name: 'Silifke', value: 'Silifke' },
    { name: 'Tarsus', value: 'Tarsus' },
    { name: 'Toroslar', value: 'Toroslar' },
    { name: 'Yenişehir', value: 'Yenişehir' },
  ],
  İstanbul: [
    { name: 'Adalar', value: 'Adalar' },
    { name: 'Arnavutköy', value: 'Arnavutköy' },
    { name: 'Ataşehir', value: 'Ataşehir' },
    { name: 'Avcılar', value: 'Avcılar' },
    { name: 'Bağcılar', value: 'Bağcılar' },
    { name: 'Bahçelievler', value: 'Bahçelievler' },
    { name: 'Bakırköy', value: 'Bakırköy' },
    { name: 'Başakşehir', value: 'Başakşehir' },
    { name: 'Bayrampaşa', value: 'Bayrampaşa' },
    { name: 'Beşiktaş', value: 'Beşiktaş' },
    { name: 'Beykoz', value: 'Beykoz' },
    { name: 'Beylikdüzü', value: 'Beylikdüzü' },
    { name: 'Beyoğlu', value: 'Beyoğlu' },
    { name: 'Büyükçekmece', value: 'Büyükçekmece' },
    { name: 'Çatalca', value: 'Çatalca' },
    { name: 'Çekmeköy', value: 'Çekmeköy' },
    { name: 'Esenler', value: 'Esenler' },
    { name: 'Esenyurt', value: 'Esenyurt' },
    { name: 'Eyüpsultan', value: 'Eyüpsultan' },
    { name: 'Fatih', value: 'Fatih' },
    { name: 'Gaziosmanpaşa', value: 'Gaziosmanpaşa' },
    { name: 'Güngören', value: 'Güngören' },
    { name: 'Kadıköy', value: 'Kadıköy' },
    { name: 'Kâğıthane', value: 'Kâğıthane' },
    { name: 'Kartal', value: 'Kartal' },
    { name: 'Küçükçekmece', value: 'Küçükçekmece' },
    { name: 'Maltepe', value: 'Maltepe' },
    { name: 'Pendik', value: 'Pendik' },
    { name: 'Sancaktepe', value: 'Sancaktepe' },
    { name: 'Sarıyer', value: 'Sarıyer' },
    { name: 'Silivri', value: 'Silivri' },
    { name: 'Sultanbeyli', value: 'Sultanbeyli' },
    { name: 'Sultangazi', value: 'Sultangazi' },
    { name: 'Şile', value: 'Şile' },
    { name: 'Şişli', value: 'Şişli' },
    { name: 'Tuzla', value: 'Tuzla' },
    { name: 'Ümraniye', value: 'Ümraniye' },
    { name: 'Üsküdar', value: 'Üsküdar' },
    { name: 'Zeytinburnu', value: 'Zeytinburnu' },
  ],
  İzmir: [
    { name: 'Aliağa', value: 'Aliağa' },
    { name: 'Balçova', value: 'Balçova' },
    { name: 'Bayındır', value: 'Bayındır' },
    { name: 'Bayraklı', value: 'Bayraklı' },
    { name: 'Bergama', value: 'Bergama' },
    { name: 'Beydağ', value: 'Beydağ' },
    { name: 'Bornova', value: 'Bornova' },
    { name: 'Buca', value: 'Buca' },
    { name: 'Çeşme', value: 'Çeşme' },
    { name: 'Çiğli', value: 'Çiğli' },
    { name: 'Dikili', value: 'Dikili' },
    { name: 'Foça', value: 'Foça' },
    { name: 'Gaziemir', value: 'Gaziemir' },
    { name: 'Güzelbahçe', value: 'Güzelbahçe' },
    { name: 'Karabağlar', value: 'Karabağlar' },
    { name: 'Karaburun', value: 'Karaburun' },
    { name: 'Karşıyaka', value: 'Karşıyaka' },
    { name: 'Kemalpaşa', value: 'Kemalpaşa' },
    { name: 'Kınık', value: 'Kınık' },
    { name: 'Kiraz', value: 'Kiraz' },
    { name: 'Konak', value: 'Konak' },
    { name: 'Menderes', value: 'Menderes' },
    { name: 'Menemen', value: 'Menemen' },
    { name: 'Narlıdere', value: 'Narlıdere' },
    { name: 'Ödemiş', value: 'Ödemiş' },
    { name: 'Seferihisar', value: 'Seferihisar' },
    { name: 'Selçuk', value: 'Selçuk' },
    { name: 'Tire', value: 'Tire' },
    { name: 'Torbalı', value: 'Torbalı' },
    { name: 'Urla', value: 'Urla' },
  ],
  Kars: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Akyaka', value: 'Akyaka' },
    { name: 'Arpaçay', value: 'Arpaçay' },
    { name: 'Digor', value: 'Digor' },
    { name: 'Kağızman', value: 'Kağızman' },
    { name: 'Sarıkamış', value: 'Sarıkamış' },
    { name: 'Selim', value: 'Selim' },
    { name: 'Susuz', value: 'Susuz' },
  ],
  Kastamonu: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Abana', value: 'Abana' },
    { name: 'Ağlı', value: 'Ağlı' },
    { name: 'Araç', value: 'Araç' },
    { name: 'Azdavay', value: 'Azdavay' },
    { name: 'Bozkurt', value: 'Bozkurt' },
    { name: 'Cide', value: 'Cide' },
    { name: 'Çatalzeytin', value: 'Çatalzeytin' },
    { name: 'Daday', value: 'Daday' },
    { name: 'Devrekani', value: 'Devrekani' },
    { name: 'Doğanyurt', value: 'Doğanyurt' },
    { name: 'Hanönü', value: 'Hanönü' },
    { name: 'İhsangazi', value: 'İhsangazi' },
    { name: 'İnebolu', value: 'İnebolu' },
    { name: 'Küre', value: 'Küre' },
    { name: 'Pınarbaşı', value: 'Pınarbaşı' },
    { name: 'Seydiler', value: 'Seydiler' },
    { name: 'Şenpazar', value: 'Şenpazar' },
    { name: 'Taşköprü', value: 'Taşköprü' },
    { name: 'Tosya', value: 'Tosya' },
  ],
  Kayseri: [
    { name: 'Akkışla', value: 'Akkışla' },
    { name: 'Bünyan', value: 'Bünyan' },
    { name: 'Develi', value: 'Develi' },
    { name: 'Felahiye', value: 'Felahiye' },
    { name: 'Hacılar', value: 'Hacılar' },
    { name: 'İncesu', value: 'İncesu' },
    { name: 'Kocasinan', value: 'Kocasinan' },
    { name: 'Melikgazi', value: 'Melikgazi' },
    { name: 'Özvatan', value: 'Özvatan' },
    { name: 'Pınarbaşı', value: 'Pınarbaşı' },
    { name: 'Sarıoğlan', value: 'Sarıoğlan' },
    { name: 'Sarız', value: 'Sarız' },
    { name: 'Talas', value: 'Talas' },
    { name: 'Tomarza', value: 'Tomarza' },
    { name: 'Yahyalı', value: 'Yahyalı' },
    { name: 'Yeşilhisar', value: 'Yeşilhisar' },
  ],
  Kırklareli: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Babaeski', value: 'Babaeski' },
    { name: 'Demirköy', value: 'Demirköy' },
    { name: 'Kofçaz', value: 'Kofçaz' },
    { name: 'Lüleburgaz', value: 'Lüleburgaz' },
    { name: 'Pehlivanköy', value: 'Pehlivanköy' },
    { name: 'Pınarhisar', value: 'Pınarhisar' },
    { name: 'Vize', value: 'Vize' },
  ],
  Kırşehir: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Akçakent', value: 'Akçakent' },
    { name: 'Akpınar', value: 'Akpınar' },
    { name: 'Boztepe', value: 'Boztepe' },
    { name: 'Çiçekdağı', value: 'Çiçekdağı' },
    { name: 'Kaman', value: 'Kaman' },
    { name: 'Mucur', value: 'Mucur' },
  ],
  Kocaeli: [
    { name: 'Başiskele', value: 'Başiskele' },
    { name: 'Çayırova', value: 'Çayırova' },
    { name: 'Darıca', value: 'Darıca' },
    { name: 'Derince', value: 'Derince' },
    { name: 'Dilovası', value: 'Dilovası' },
    { name: 'Gebze', value: 'Gebze' },
    { name: 'Gölcük', value: 'Gölcük' },
    { name: 'İzmit', value: 'İzmit' },
    { name: 'Kandıra', value: 'Kandıra' },
    { name: 'Karamürsel', value: 'Karamürsel' },
    { name: 'Kartepe', value: 'Kartepe' },
    { name: 'Körfez', value: 'Körfez' },
  ],
  Konya: [
    { name: 'Ahırlı', value: 'Ahırlı' },
    { name: 'Akören', value: 'Akören' },
    { name: 'Akşehir', value: 'Akşehir' },
    { name: 'Altınekin', value: 'Altınekin' },
    { name: 'Beyşehir', value: 'Beyşehir' },
    { name: 'Bozkır', value: 'Bozkır' },
    { name: 'Cihanbeyli', value: 'Cihanbeyli' },
    { name: 'Çeltik', value: 'Çeltik' },
    { name: 'Çumra', value: 'Çumra' },
    { name: 'Derbent', value: 'Derbent' },
    { name: 'Derebucak', value: 'Derebucak' },
    { name: 'Doğanhisar', value: 'Doğanhisar' },
    { name: 'Emirgazi', value: 'Emirgazi' },
    { name: 'Ereğli', value: 'Ereğli' },
    { name: 'Güneysınır', value: 'Güneysınır' },
    { name: 'Hadim', value: 'Hadim' },
    { name: 'Halkapınar', value: 'Halkapınar' },
    { name: 'Hüyük', value: 'Hüyük' },
    { name: 'Ilgın', value: 'Ilgın' },
    { name: 'Kadınhanı', value: 'Kadınhanı' },
    { name: 'Karapınar', value: 'Karapınar' },
    { name: 'Karatay', value: 'Karatay' },
    { name: 'Kulu', value: 'Kulu' },
    { name: 'Meram', value: 'Meram' },
    { name: 'Sarayönü', value: 'Sarayönü' },
    { name: 'Selçuklu', value: 'Selçuklu' },
    { name: 'Seydişehir', value: 'Seydişehir' },
    { name: 'Taşkent', value: 'Taşkent' },
    { name: 'Tuzlukçu', value: 'Tuzlukçu' },
    { name: 'Yalıhüyük', value: 'Yalıhüyük' },
    { name: 'Yunak', value: 'Yunak' },
  ],
  Kütahya: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Altıntaş', value: 'Altıntaş' },
    { name: 'Aslanapa', value: 'Aslanapa' },
    { name: 'Çavdarhisar', value: 'Çavdarhisar' },
    { name: 'Domaniç', value: 'Domaniç' },
    { name: 'Dumlupınar', value: 'Dumlupınar' },
    { name: 'Emet', value: 'Emet' },
    { name: 'Gediz', value: 'Gediz' },
    { name: 'Hisarcık', value: 'Hisarcık' },
    { name: 'Pazarlar', value: 'Pazarlar' },
    { name: 'Şaphane', value: 'Şaphane' },
    { name: 'Simav', value: 'Simav' },
    { name: 'Tavşanlı', value: 'Tavşanlı' },
  ],
  Malatya: [
    { name: 'Akçadağ', value: 'Akçadağ' },
    { name: 'Arapgir', value: 'Arapgir' },
    { name: 'Arguvan', value: 'Arguvan' },
    { name: 'Battalgazi', value: 'Battalgazi' },
    { name: 'Darende', value: 'Darende' },
    { name: 'Doğanşehir', value: 'Doğanşehir' },
    { name: 'Doğanyol', value: 'Doğanyol' },
    { name: 'Hekimhan', value: 'Hekimhan' },
    { name: 'Kale', value: 'Kale' },
    { name: 'Kuluncak', value: 'Kuluncak' },
    { name: 'Pütürge', value: 'Pütürge' },
    { name: 'Yazıhan', value: 'Yazıhan' },
    { name: 'Yeşilyurt', value: 'Yeşilyurt' },
  ],
  Manisa: [
    { name: 'Ahmetli', value: 'Ahmetli' },
    { name: 'Akhisar', value: 'Akhisar' },
    { name: 'Alaşehir', value: 'Alaşehir' },
    { name: 'Demirci', value: 'Demirci' },
    { name: 'Gölmarmara', value: 'Gölmarmara' },
    { name: 'Gördes', value: 'Gördes' },
    { name: 'Kırkağaç', value: 'Kırkağaç' },
    { name: 'Köprübaşı', value: 'Köprübaşı' },
    { name: 'Kula', value: 'Kula' },
    { name: 'Salihli', value: 'Salihli' },
    { name: 'Sarıgöl', value: 'Sarıgöl' },
    { name: 'Saruhanlı', value: 'Saruhanlı' },
    { name: 'Selendi', value: 'Selendi' },
    { name: 'Soma', value: 'Soma' },
    { name: 'Şehzadeler', value: 'Şehzadeler' },
    { name: 'Turgutlu', value: 'Turgutlu' },
    { name: 'Yunusemre', value: 'Yunusemre' },
  ],
  Kahramanmaraş: [
    { name: 'Afşin', value: 'Afşin' },
    { name: 'Andırın', value: 'Andırın' },
    { name: 'Çağlayancerit', value: 'Çağlayancerit' },
    { name: 'Dulkadiroğlu', value: 'Dulkadiroğlu' },
    { name: 'Ekinözü', value: 'Ekinözü' },
    { name: 'Elbistan', value: 'Elbistan' },
    { name: 'Göksun', value: 'Göksun' },
    { name: 'Nurhak', value: 'Nurhak' },
    { name: 'Onikişubat', value: 'Onikişubat' },
    { name: 'Pazarcık', value: 'Pazarcık' },
    { name: 'Türkoğlu', value: 'Türkoğlu' },
  ],
  Mardin: [
    { name: 'Artuklu', value: 'Artuklu' },
    { name: 'Dargeçit', value: 'Dargeçit' },
    { name: 'Derik', value: 'Derik' },
    { name: 'Kızıltepe', value: 'Kızıltepe' },
    { name: 'Mazıdağı', value: 'Mazıdağı' },
    { name: 'Midyat', value: 'Midyat' },
    { name: 'Nusaybin', value: 'Nusaybin' },
    { name: 'Ömerli', value: 'Ömerli' },
    { name: 'Savur', value: 'Savur' },
    { name: 'Yeşilli', value: 'Yeşilli' },
  ],
  Muğla: [
    { name: 'Bodrum', value: 'Bodrum' },
    { name: 'Dalaman', value: 'Dalaman' },
    { name: 'Datça', value: 'Datça' },
    { name: 'Fethiye', value: 'Fethiye' },
    { name: 'Kavaklıdere', value: 'Kavaklıdere' },
    { name: 'Köyceğiz', value: 'Köyceğiz' },
    { name: 'Marmaris', value: 'Marmaris' },
    { name: 'Menteşe', value: 'Menteşe' },
    { name: 'Milas', value: 'Milas' },
    { name: 'Ortaca', value: 'Ortaca' },
    { name: 'Seydikemer', value: 'Seydikemer' },
    { name: 'Ula', value: 'Ula' },
    { name: 'Yatağan', value: 'Yatağan' },
  ],
  Muş: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Bulanık', value: 'Bulanık' },
    { name: 'Hasköy', value: 'Hasköy' },
    { name: 'Korkut', value: 'Korkut' },
    { name: 'Malazgirt', value: 'Malazgirt' },
    { name: 'Varto', value: 'Varto' },
  ],
  Nevşehir: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Acıgöl', value: 'Acıgöl' },
    { name: 'Avanos', value: 'Avanos' },
    { name: 'Derinkuyu', value: 'Derinkuyu' },
    { name: 'Gülşehir', value: 'Gülşehir' },
    { name: 'Hacıbektaş', value: 'Hacıbektaş' },
    { name: 'Kozaklı', value: 'Kozaklı' },
    { name: 'Ürgüp', value: 'Ürgüp' },
  ],
  Niğde: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Altunhisar', value: 'Altunhisar' },
    { name: 'Bor', value: 'Bor' },
    { name: 'Çamardı', value: 'Çamardı' },
    { name: 'Çiftlik', value: 'Çiftlik' },
    { name: 'Ulukışla', value: 'Ulukışla' },
  ],
  Ordu: [
    { name: 'Akkuş', value: 'Akkuş' },
    { name: 'Altınordu', value: 'Altınordu' },
    { name: 'Aybastı', value: 'Aybastı' },
    { name: 'Çamaş', value: 'Çamaş' },
    { name: 'Çatalpınar', value: 'Çatalpınar' },
    { name: 'Çaybaşı', value: 'Çaybaşı' },
    { name: 'Fatsa', value: 'Fatsa' },
    { name: 'Gölköy', value: 'Gölköy' },
    { name: 'Gülyalı', value: 'Gülyalı' },
    { name: 'Gürgentepe', value: 'Gürgentepe' },
    { name: 'İkizce', value: 'İkizce' },
    { name: 'Kabadüz', value: 'Kabadüz' },
    { name: 'Kabataş', value: 'Kabataş' },
    { name: 'Korgan', value: 'Korgan' },
    { name: 'Kumru', value: 'Kumru' },
    { name: 'Mesudiye', value: 'Mesudiye' },
    { name: 'Perşembe', value: 'Perşembe' },
    { name: 'Ulubey', value: 'Ulubey' },
    { name: 'Ünye', value: 'Ünye' },
  ],
  Rize: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ardeşen', value: 'Ardeşen' },
    { name: 'Çamlıhemşin', value: 'Çamlıhemşin' },
    { name: 'Çayeli', value: 'Çayeli' },
    { name: 'Derepazarı', value: 'Derepazarı' },
    { name: 'Fındıklı', value: 'Fındıklı' },
    { name: 'Güneysu', value: 'Güneysu' },
    { name: 'Hemşin', value: 'Hemşin' },
    { name: 'İkizdere', value: 'İkizdere' },
    { name: 'İyidere', value: 'İyidere' },
    { name: 'Kalkandere', value: 'Kalkandere' },
    { name: 'Pazar', value: 'Pazar' },
  ],
  Sakarya: [
    { name: 'Adapazarı', value: 'Adapazarı' },
    { name: 'Akyazı', value: 'Akyazı' },
    { name: 'Arifiye', value: 'Arifiye' },
    { name: 'Erenler', value: 'Erenler' },
    { name: 'Ferizli', value: 'Ferizli' },
    { name: 'Geyve', value: 'Geyve' },
    { name: 'Hendek', value: 'Hendek' },
    { name: 'Karapürçek', value: 'Karapürçek' },
    { name: 'Karasu', value: 'Karasu' },
    { name: 'Kaynarca', value: 'Kaynarca' },
    { name: 'Kocaali', value: 'Kocaali' },
    { name: 'Pamukova', value: 'Pamukova' },
    { name: 'Sapanca', value: 'Sapanca' },
    { name: 'Serdivan', value: 'Serdivan' },
    { name: 'Söğütlü', value: 'Söğütlü' },
    { name: 'Taraklı', value: 'Taraklı' },
  ],
  Samsun: [
    { name: '19 Mayıs', value: '19 Mayıs' },
    { name: 'Alaçam', value: 'Alaçam' },
    { name: 'Asarcık', value: 'Asarcık' },
    { name: 'Atakum', value: 'Atakum' },
    { name: 'Ayvacık', value: 'Ayvacık' },
    { name: 'Bafra', value: 'Bafra' },
    { name: 'Canik', value: 'Canik' },
    { name: 'Çarşamba', value: 'Çarşamba' },
    { name: 'Havza', value: 'Havza' },
    { name: 'İlkadım', value: 'İlkadım' },
    { name: 'Kavak', value: 'Kavak' },
    { name: 'Ladik', value: 'Ladik' },
    { name: 'Salıpazarı', value: 'Salıpazarı' },
    { name: 'Tekkeköy', value: 'Tekkeköy' },
    { name: 'Terme', value: 'Terme' },
    { name: 'Vezirköprü', value: 'Vezirköprü' },
    { name: 'Yakakent', value: 'Yakakent' },
  ],
  Siirt: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Baykan', value: 'Baykan' },
    { name: 'Eruh', value: 'Eruh' },
    { name: 'Kurtalan', value: 'Kurtalan' },
    { name: 'Pervari', value: 'Pervari' },
    { name: 'Şirvan', value: 'Şirvan' },
    { name: 'Tillo', value: 'Tillo' },
  ],
  Sinop: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ayancık', value: 'Ayancık' },
    { name: 'Boyabat', value: 'Boyabat' },
    { name: 'Dikmen', value: 'Dikmen' },
    { name: 'Durağan', value: 'Durağan' },
    { name: 'Erfelek', value: 'Erfelek' },
    { name: 'Gerze', value: 'Gerze' },
    { name: 'Saraydüzü', value: 'Saraydüzü' },
    { name: 'Türkeli', value: 'Türkeli' },
  ],
  Sivas: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Akıncılar', value: 'Akıncılar' },
    { name: 'Altınyayla', value: 'Altınyayla' },
    { name: 'Divriği', value: 'Divriği' },
    { name: 'Doğanşar', value: 'Doğanşar' },
    { name: 'Gemerek', value: 'Gemerek' },
    { name: 'Gölova', value: 'Gölova' },
    { name: 'Gürün', value: 'Gürün' },
    { name: 'Hafik', value: 'Hafik' },
    { name: 'İmranlı', value: 'İmranlı' },
    { name: 'Kangal', value: 'Kangal' },
    { name: 'Koyulhisar', value: 'Koyulhisar' },
    { name: 'Suşehri', value: 'Suşehri' },
    { name: 'Şarkışla', value: 'Şarkışla' },
    { name: 'Ulaş', value: 'Ulaş' },
    { name: 'Yıldızeli', value: 'Yıldızeli' },
    { name: 'Zara', value: 'Zara' },
  ],
  Tekirdağ: [
    { name: 'Çerkezköy', value: 'Çerkezköy' },
    { name: 'Çorlu', value: 'Çorlu' },
    { name: 'Ergene', value: 'Ergene' },
    { name: 'Hayrabolu', value: 'Hayrabolu' },
    { name: 'Kapaklı', value: 'Kapaklı' },
    { name: 'Malkara', value: 'Malkara' },
    { name: 'Marmaraereğlisi', value: 'Marmaraereğlisi' },
    { name: 'Muratlı', value: 'Muratlı' },
    { name: 'Saray', value: 'Saray' },
    { name: 'Süleymanpaşa', value: 'Süleymanpaşa' },
    { name: 'Şarköy', value: 'Şarköy' },
  ],
  Tokat: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Almus', value: 'Almus' },
    { name: 'Artova', value: 'Artova' },
    { name: 'Başçiftlik', value: 'Başçiftlik' },
    { name: 'Erbaa', value: 'Erbaa' },
    { name: 'Niksar', value: 'Niksar' },
    { name: 'Pazar', value: 'Pazar' },
    { name: 'Reşadiye', value: 'Reşadiye' },
    { name: 'Sulusaray', value: 'Sulusaray' },
    { name: 'Turhal', value: 'Turhal' },
    { name: 'Yeşilyurt', value: 'Yeşilyurt' },
    { name: 'Zile', value: 'Zile' },
  ],
  Trabzon: [
    { name: 'Akçaabat', value: 'Akçaabat' },
    { name: 'Araklı', value: 'Araklı' },
    { name: 'Arsin', value: 'Arsin' },
    { name: 'Beşikdüzü', value: 'Beşikdüzü' },
    { name: 'Çarşıbaşı', value: 'Çarşıbaşı' },
    { name: 'Çaykara', value: 'Çaykara' },
    { name: 'Dernekpazarı', value: 'Dernekpazarı' },
    { name: 'Düzköy', value: 'Düzköy' },
    { name: 'Hayrat', value: 'Hayrat' },
    { name: 'Köprübaşı', value: 'Köprübaşı' },
    { name: 'Maçka', value: 'Maçka' },
    { name: 'Of', value: 'Of' },
    { name: 'Ortahisar', value: 'Ortahisar' },
    { name: 'Sürmene', value: 'Sürmene' },
    { name: 'Şalpazarı', value: 'Şalpazarı' },
    { name: 'Tonya', value: 'Tonya' },
    { name: 'Vakfıkebir', value: 'Vakfıkebir' },
    { name: 'Yomra', value: 'Yomra' },
  ],
  Tunceli: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Çemişgezek', value: 'Çemişgezek' },
    { name: 'Hozat', value: 'Hozat' },
    { name: 'Mazgirt', value: 'Mazgirt' },
    { name: 'Nazımiye', value: 'Nazımiye' },
    { name: 'Ovacık', value: 'Ovacık' },
    { name: 'Pertek', value: 'Pertek' },
    { name: 'Pülümür', value: 'Pülümür' },
  ],
  Şanlıurfa: [
    { name: 'Akçakale', value: 'Akçakale' },
    { name: 'Birecik', value: 'Birecik' },
    { name: 'Bozova', value: 'Bozova' },
    { name: 'Ceylanpınar', value: 'Ceylanpınar' },
    { name: 'Eyyübiye', value: 'Eyyübiye' },
    { name: 'Halfeti', value: 'Halfeti' },
    { name: 'Haliliye', value: 'Haliliye' },
    { name: 'Harran', value: 'Harran' },
    { name: 'Hilvan', value: 'Hilvan' },
    { name: 'Karaköprü', value: 'Karaköprü' },
    { name: 'Siverek', value: 'Siverek' },
    { name: 'Suruç', value: 'Suruç' },
    { name: 'Viranşehir', value: 'Viranşehir' },
  ],
  Uşak: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Banaz', value: 'Banaz' },
    { name: 'Eşme', value: 'Eşme' },
    { name: 'Karahallı', value: 'Karahallı' },
    { name: 'Sivaslı', value: 'Sivaslı' },
    { name: 'Ulubey', value: 'Ulubey' },
  ],
  Van: [
    { name: 'Bahçesaray', value: 'Bahçesaray' },
    { name: 'Başkale', value: 'Başkale' },
    { name: 'Çaldıran', value: 'Çaldıran' },
    { name: 'Çatak', value: 'Çatak' },
    { name: 'Edremit', value: 'Edremit' },
    { name: 'Erciş', value: 'Erciş' },
    { name: 'Gevaş', value: 'Gevaş' },
    { name: 'Gürpınar', value: 'Gürpınar' },
    { name: 'İpekyolu', value: 'İpekyolu' },
    { name: 'Muradiye', value: 'Muradiye' },
    { name: 'Özalp', value: 'Özalp' },
    { name: 'Saray', value: 'Saray' },
    { name: 'Tuşba', value: 'Tuşba' },
  ],
  Yozgat: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Akdağmadeni', value: 'Akdağmadeni' },
    { name: 'Aydıncık', value: 'Aydıncık' },
    { name: 'Boğazlıyan', value: 'Boğazlıyan' },
    { name: 'Çandır', value: 'Çandır' },
    { name: 'Çayıralan', value: 'Çayıralan' },
    { name: 'Çekerek', value: 'Çekerek' },
    { name: 'Kadışehri', value: 'Kadışehri' },
    { name: 'Saraykent', value: 'Saraykent' },
    { name: 'Sarıkaya', value: 'Sarıkaya' },
    { name: 'Sorgun', value: 'Sorgun' },
    { name: 'Şefaatli', value: 'Şefaatli' },
    { name: 'Yenifakılı', value: 'Yenifakılı' },
    { name: 'Yerköy', value: 'Yerköy' },
  ],
  Zonguldak: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Alaplı', value: 'Alaplı' },
    { name: 'Çaycuma', value: 'Çaycuma' },
    { name: 'Devrek', value: 'Devrek' },
    { name: 'Gökçebey', value: 'Gökçebey' },
    { name: 'Karadeniz Ereğli', value: 'Karadeniz Ereğli' },
    { name: 'Kilimli', value: 'Kilimli' },
    { name: 'Kozlu', value: 'Kozlu' },
  ],
  Aksaray: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ağaçören', value: 'Ağaçören' },
    { name: 'Eskil', value: 'Eskil' },
    { name: 'Gülağaç', value: 'Gülağaç' },
    { name: 'Güzelyurt', value: 'Güzelyurt' },
    { name: 'Ortaköy', value: 'Ortaköy' },
    { name: 'Sarıyahşi', value: 'Sarıyahşi' },
    { name: 'Sultanhanı', value: 'Sultanhanı' },
  ],
  Bayburt: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Aydıntepe', value: 'Aydıntepe' },
    { name: 'Demirözü', value: 'Demirözü' },
  ],
  Karaman: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Ayrancı', value: 'Ayrancı' },
    { name: 'Başyayla', value: 'Başyayla' },
    { name: 'Ermenek', value: 'Ermenek' },
    { name: 'Kazımkarabekir', value: 'Kazımkarabekir' },
    { name: 'Sarıveliler', value: 'Sarıveliler' },
  ],
  Kırıkkale: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Bahşili', value: 'Bahşili' },
    { name: 'Balışeyh', value: 'Balışeyh' },
    { name: 'Çelebi', value: 'Çelebi' },
    { name: 'Delice', value: 'Delice' },
    { name: 'Karakeçili', value: 'Karakeçili' },
    { name: 'Keskin', value: 'Keskin' },
    { name: 'Sulakyurt', value: 'Sulakyurt' },
  ],
  Batman: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Beşiri', value: 'Beşiri' },
    { name: 'Gercüş', value: 'Gercüş' },
    { name: 'Hasankeyf', value: 'Hasankeyf' },
    { name: 'Kozluk', value: 'Kozluk' },
    { name: 'Sason', value: 'Sason' },
  ],
  Şırnak: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Beytüşşebap', value: 'Beytüşşebap' },
    { name: 'Cizre', value: 'Cizre' },
    { name: 'Güçlükonak', value: 'Güçlükonak' },
    { name: 'İdil', value: 'İdil' },
    { name: 'Silopi', value: 'Silopi' },
    { name: 'Uludere', value: 'Uludere' },
  ],
  Bartın: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Amasra', value: 'Amasra' },
    { name: 'Kurucaşile', value: 'Kurucaşile' },
    { name: 'Ulus', value: 'Ulus' },
  ],
  Ardahan: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Çıldır', value: 'Çıldır' },
    { name: 'Damal', value: 'Damal' },
    { name: 'Göle', value: 'Göle' },
    { name: 'Hanak', value: 'Hanak' },
    { name: 'Posof', value: 'Posof' },
  ],
  Iğdır: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Aralık', value: 'Aralık' },
    { name: 'Karakoyunlu', value: 'Karakoyunlu' },
    { name: 'Tuzluca', value: 'Tuzluca' },
  ],
  Yalova: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Altınova', value: 'Altınova' },
    { name: 'Armutlu', value: 'Armutlu' },
    { name: 'Çınarcık', value: 'Çınarcık' },
    { name: 'Çiftlikköy', value: 'Çiftlikköy' },
    { name: 'Termal', value: 'Termal' },
  ],
  Karabük: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Eflani', value: 'Eflani' },
    { name: 'Eskipazar', value: 'Eskipazar' },
    { name: 'Ovacık', value: 'Ovacık' },
    { name: 'Safranbolu', value: 'Safranbolu' },
    { name: 'Yenice', value: 'Yenice' },
  ],
  Kilis: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Elbeyli', value: 'Elbeyli' },
    { name: 'Musabeyli', value: 'Musabeyli' },
    { name: 'Polateli', value: 'Polateli' },
  ],
  Osmaniye: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Bahçe', value: 'Bahçe' },
    { name: 'Düziçi', value: 'Düziçi' },
    { name: 'Hasanbeyli', value: 'Hasanbeyli' },
    { name: 'Kadirli', value: 'Kadirli' },
    { name: 'Sumbas', value: 'Sumbas' },
    { name: 'Toprakkale', value: 'Toprakkale' },
  ],
  Düzce: [
    { name: 'Merkez', value: 'Merkez' },
    { name: 'Akçakoca', value: 'Akçakoca' },
    { name: 'Cumayeri', value: 'Cumayeri' },
    { name: 'Çilimli', value: 'Çilimli' },
    { name: 'Gölyaka', value: 'Gölyaka' },
    { name: 'Gümüşova', value: 'Gümüşova' },
    { name: 'Kaynaşlı', value: 'Kaynaşlı' },
    { name: 'Yığılca', value: 'Yığılca' },
  ],
}
